/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotInvitedRouteImport } from './routes/not-invited'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppMoneyRouteImport } from './routes/_app/money'
import { Route as AppPantryRouteImport } from './routes/_app/pantry'
import { Route as AppPlacesRouteImport } from './routes/_app/places'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppThingsRouteImport } from './routes/_app/things'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsDiagnosticsRouteImport } from './routes/_app/settings/diagnostics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotInvitedRoute = NotInvitedRouteImport.update({
  id: '/not-invited',
  path: '/not-invited',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppThingsRoute = AppThingsRouteImport.update({
  id: '/things',
  path: '/things',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDiagnosticsRoute = AppSettingsDiagnosticsRouteImport.update({
  id: '/settings/diagnostics',
  path: '/settings/diagnostics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/not-invited': typeof NotInvitedRoute
  '/insights': typeof AppInsightsRoute
  '/money': typeof AppMoneyRoute
  '/pantry': typeof AppPantryRoute
  '/places': typeof AppPlacesRoute
  '/scan': typeof AppScanRoute
  '/things': typeof AppThingsRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/not-invited': typeof NotInvitedRoute
  '/insights': typeof AppInsightsRoute
  '/money': typeof AppMoneyRoute
  '/pantry': typeof AppPantryRoute
  '/places': typeof AppPlacesRoute
  '/scan': typeof AppScanRoute
  '/things': typeof AppThingsRoute
  '/': typeof AppIndexRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/not-invited': typeof NotInvitedRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/money': typeof AppMoneyRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/places': typeof AppPlacesRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/things': typeof AppThingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-invited'
    | '/insights'
    | '/money'
    | '/pantry'
    | '/places'
    | '/scan'
    | '/things'
    | '/settings/diagnostics'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/not-invited'
    | '/insights'
    | '/money'
    | '/pantry'
    | '/places'
    | '/scan'
    | '/things'
    | '/'
    | '/settings/diagnostics'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/not-invited'
    | '/_app/insights'
    | '/_app/money'
    | '/_app/pantry'
    | '/_app/places'
    | '/_app/scan'
    | '/_app/things'
    | '/_app/'
    | '/_app/settings/diagnostics'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotInvitedRoute: typeof NotInvitedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-invited': {
      id: '/not-invited'
      path: '/not-invited'
      fullPath: '/not-invited'
      preLoaderRoute: typeof NotInvitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/places': {
      id: '/_app/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/things': {
      id: '/_app/things'
      path: '/things'
      fullPath: '/things'
      preLoaderRoute: typeof AppThingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/diagnostics': {
      id: '/_app/settings/diagnostics'
      path: '/settings/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof AppSettingsDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInsightsRoute: typeof AppInsightsRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppPantryRoute: typeof AppPantryRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppScanRoute: typeof AppScanRoute
  AppThingsRoute: typeof AppThingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsDiagnosticsRoute: typeof AppSettingsDiagnosticsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInsightsRoute: AppInsightsRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppPantryRoute: AppPantryRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppScanRoute: AppScanRoute,
  AppThingsRoute: AppThingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsDiagnosticsRoute: AppSettingsDiagnosticsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  NotInvitedRoute: NotInvitedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
