/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotInvitedRouteImport } from './routes/not-invited'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppThingsRouteImport } from './routes/_app/things'
import { Route as AppMoneyIndexRouteImport } from './routes/_app/money/index'
import { Route as AppMoneyImportRouteImport } from './routes/_app/money/import'
import { Route as AppMoneyInboxRouteImport } from './routes/_app/money/inbox'
import { Route as AppPantryIndexRouteImport } from './routes/_app/pantry/index'
import { Route as AppPantryProductIdRouteImport } from './routes/_app/pantry/$productId'
import { Route as AppPantryJournalRouteImport } from './routes/_app/pantry/journal'
import { Route as AppPantryListRouteImport } from './routes/_app/pantry/list'
import { Route as AppPlacesIndexRouteImport } from './routes/_app/places/index'
import { Route as AppPlacesPlaceIdRouteImport } from './routes/_app/places/$placeId'
import { Route as AppPlacesLabelsRouteImport } from './routes/_app/places/labels'
import { Route as AppSCodeRouteImport } from './routes/_app/s.$code'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsCategoriesRouteImport } from './routes/_app/settings/categories'
import { Route as AppSettingsDevicesRouteImport } from './routes/_app/settings/devices'
import { Route as AppSettingsDiagnosticsRouteImport } from './routes/_app/settings/diagnostics'
import { Route as AppSettingsUnitsRouteImport } from './routes/_app/settings/units'
import { Route as AppMoneyAccountsIndexRouteImport } from './routes/_app/money/accounts/index'
import { Route as AppMoneyAccountsAccountIdRouteImport } from './routes/_app/money/accounts/$accountId'
import { Route as AppMoneyTxTxIdRouteImport } from './routes/_app/money/tx.$txId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotInvitedRoute = NotInvitedRouteImport.update({
  id: '/not-invited',
  path: '/not-invited',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppThingsRoute = AppThingsRouteImport.update({
  id: '/things',
  path: '/things',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyIndexRoute = AppMoneyIndexRouteImport.update({
  id: '/money/',
  path: '/money/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyImportRoute = AppMoneyImportRouteImport.update({
  id: '/money/import',
  path: '/money/import',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyInboxRoute = AppMoneyInboxRouteImport.update({
  id: '/money/inbox',
  path: '/money/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryIndexRoute = AppPantryIndexRouteImport.update({
  id: '/pantry/',
  path: '/pantry/',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryProductIdRoute = AppPantryProductIdRouteImport.update({
  id: '/pantry/$productId',
  path: '/pantry/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryJournalRoute = AppPantryJournalRouteImport.update({
  id: '/pantry/journal',
  path: '/pantry/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryListRoute = AppPantryListRouteImport.update({
  id: '/pantry/list',
  path: '/pantry/list',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesIndexRoute = AppPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesPlaceIdRoute = AppPlacesPlaceIdRouteImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesLabelsRoute = AppPlacesLabelsRouteImport.update({
  id: '/places/labels',
  path: '/places/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppSCodeRoute = AppSCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCategoriesRoute = AppSettingsCategoriesRouteImport.update({
  id: '/settings/categories',
  path: '/settings/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDevicesRoute = AppSettingsDevicesRouteImport.update({
  id: '/settings/devices',
  path: '/settings/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDiagnosticsRoute = AppSettingsDiagnosticsRouteImport.update({
  id: '/settings/diagnostics',
  path: '/settings/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUnitsRoute = AppSettingsUnitsRouteImport.update({
  id: '/settings/units',
  path: '/settings/units',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyAccountsIndexRoute = AppMoneyAccountsIndexRouteImport.update({
  id: '/money/accounts/',
  path: '/money/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyAccountsAccountIdRoute =
  AppMoneyAccountsAccountIdRouteImport.update({
    id: '/money/accounts/$accountId',
    path: '/money/accounts/$accountId',
    getParentRoute: () => AppRoute,
  } as any)
const AppMoneyTxTxIdRoute = AppMoneyTxTxIdRouteImport.update({
  id: '/money/tx/$txId',
  path: '/money/tx/$txId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/not-invited': typeof NotInvitedRoute
  '/insights': typeof AppInsightsRoute
  '/scan': typeof AppScanRoute
  '/things': typeof AppThingsRoute
  '/money/import': typeof AppMoneyImportRoute
  '/money/inbox': typeof AppMoneyInboxRoute
  '/pantry/$productId': typeof AppPantryProductIdRoute
  '/pantry/journal': typeof AppPantryJournalRoute
  '/pantry/list': typeof AppPantryListRoute
  '/places/$placeId': typeof AppPlacesPlaceIdRoute
  '/places/labels': typeof AppPlacesLabelsRoute
  '/s/$code': typeof AppSCodeRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/devices': typeof AppSettingsDevicesRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/units': typeof AppSettingsUnitsRoute
  '/money/': typeof AppMoneyIndexRoute
  '/pantry/': typeof AppPantryIndexRoute
  '/places/': typeof AppPlacesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/money/accounts/$accountId': typeof AppMoneyAccountsAccountIdRoute
  '/money/tx/$txId': typeof AppMoneyTxTxIdRoute
  '/money/accounts/': typeof AppMoneyAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/not-invited': typeof NotInvitedRoute
  '/insights': typeof AppInsightsRoute
  '/scan': typeof AppScanRoute
  '/things': typeof AppThingsRoute
  '/': typeof AppIndexRoute
  '/money/import': typeof AppMoneyImportRoute
  '/money/inbox': typeof AppMoneyInboxRoute
  '/pantry/$productId': typeof AppPantryProductIdRoute
  '/pantry/journal': typeof AppPantryJournalRoute
  '/pantry/list': typeof AppPantryListRoute
  '/places/$placeId': typeof AppPlacesPlaceIdRoute
  '/places/labels': typeof AppPlacesLabelsRoute
  '/s/$code': typeof AppSCodeRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/devices': typeof AppSettingsDevicesRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/units': typeof AppSettingsUnitsRoute
  '/money': typeof AppMoneyIndexRoute
  '/pantry': typeof AppPantryIndexRoute
  '/places': typeof AppPlacesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/money/accounts/$accountId': typeof AppMoneyAccountsAccountIdRoute
  '/money/tx/$txId': typeof AppMoneyTxTxIdRoute
  '/money/accounts': typeof AppMoneyAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/not-invited': typeof NotInvitedRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/things': typeof AppThingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/money/import': typeof AppMoneyImportRoute
  '/_app/money/inbox': typeof AppMoneyInboxRoute
  '/_app/pantry/$productId': typeof AppPantryProductIdRoute
  '/_app/pantry/journal': typeof AppPantryJournalRoute
  '/_app/pantry/list': typeof AppPantryListRoute
  '/_app/places/$placeId': typeof AppPlacesPlaceIdRoute
  '/_app/places/labels': typeof AppPlacesLabelsRoute
  '/_app/s/$code': typeof AppSCodeRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/categories': typeof AppSettingsCategoriesRoute
  '/_app/settings/devices': typeof AppSettingsDevicesRoute
  '/_app/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/_app/settings/units': typeof AppSettingsUnitsRoute
  '/_app/money/': typeof AppMoneyIndexRoute
  '/_app/pantry/': typeof AppPantryIndexRoute
  '/_app/places/': typeof AppPlacesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/money/accounts/$accountId': typeof AppMoneyAccountsAccountIdRoute
  '/_app/money/tx/$txId': typeof AppMoneyTxTxIdRoute
  '/_app/money/accounts/': typeof AppMoneyAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-invited'
    | '/insights'
    | '/scan'
    | '/things'
    | '/money/import'
    | '/money/inbox'
    | '/pantry/$productId'
    | '/pantry/journal'
    | '/pantry/list'
    | '/places/$placeId'
    | '/places/labels'
    | '/s/$code'
    | '/settings/appearance'
    | '/settings/categories'
    | '/settings/devices'
    | '/settings/diagnostics'
    | '/settings/units'
    | '/money/'
    | '/pantry/'
    | '/places/'
    | '/settings/'
    | '/money/accounts/$accountId'
    | '/money/tx/$txId'
    | '/money/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/not-invited'
    | '/insights'
    | '/scan'
    | '/things'
    | '/'
    | '/money/import'
    | '/money/inbox'
    | '/pantry/$productId'
    | '/pantry/journal'
    | '/pantry/list'
    | '/places/$placeId'
    | '/places/labels'
    | '/s/$code'
    | '/settings/appearance'
    | '/settings/categories'
    | '/settings/devices'
    | '/settings/diagnostics'
    | '/settings/units'
    | '/money'
    | '/pantry'
    | '/places'
    | '/settings'
    | '/money/accounts/$accountId'
    | '/money/tx/$txId'
    | '/money/accounts'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/not-invited'
    | '/_app/insights'
    | '/_app/scan'
    | '/_app/things'
    | '/_app/'
    | '/_app/money/import'
    | '/_app/money/inbox'
    | '/_app/pantry/$productId'
    | '/_app/pantry/journal'
    | '/_app/pantry/list'
    | '/_app/places/$placeId'
    | '/_app/places/labels'
    | '/_app/s/$code'
    | '/_app/settings/appearance'
    | '/_app/settings/categories'
    | '/_app/settings/devices'
    | '/_app/settings/diagnostics'
    | '/_app/settings/units'
    | '/_app/money/'
    | '/_app/pantry/'
    | '/_app/places/'
    | '/_app/settings/'
    | '/_app/money/accounts/$accountId'
    | '/_app/money/tx/$txId'
    | '/_app/money/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotInvitedRoute: typeof NotInvitedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-invited': {
      id: '/not-invited'
      path: '/not-invited'
      fullPath: '/not-invited'
      preLoaderRoute: typeof NotInvitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/things': {
      id: '/_app/things'
      path: '/things'
      fullPath: '/things'
      preLoaderRoute: typeof AppThingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/': {
      id: '/_app/money/'
      path: '/money'
      fullPath: '/money/'
      preLoaderRoute: typeof AppMoneyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/import': {
      id: '/_app/money/import'
      path: '/money/import'
      fullPath: '/money/import'
      preLoaderRoute: typeof AppMoneyImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/inbox': {
      id: '/_app/money/inbox'
      path: '/money/inbox'
      fullPath: '/money/inbox'
      preLoaderRoute: typeof AppMoneyInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry/': {
      id: '/_app/pantry/'
      path: '/pantry'
      fullPath: '/pantry/'
      preLoaderRoute: typeof AppPantryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry/$productId': {
      id: '/_app/pantry/$productId'
      path: '/pantry/$productId'
      fullPath: '/pantry/$productId'
      preLoaderRoute: typeof AppPantryProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry/journal': {
      id: '/_app/pantry/journal'
      path: '/pantry/journal'
      fullPath: '/pantry/journal'
      preLoaderRoute: typeof AppPantryJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry/list': {
      id: '/_app/pantry/list'
      path: '/pantry/list'
      fullPath: '/pantry/list'
      preLoaderRoute: typeof AppPantryListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/places/': {
      id: '/_app/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof AppPlacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/places/$placeId': {
      id: '/_app/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof AppPlacesPlaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/places/labels': {
      id: '/_app/places/labels'
      path: '/places/labels'
      fullPath: '/places/labels'
      preLoaderRoute: typeof AppPlacesLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$code': {
      id: '/_app/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof AppSCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/categories': {
      id: '/_app/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AppSettingsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/devices': {
      id: '/_app/settings/devices'
      path: '/settings/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof AppSettingsDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/diagnostics': {
      id: '/_app/settings/diagnostics'
      path: '/settings/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof AppSettingsDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/units': {
      id: '/_app/settings/units'
      path: '/settings/units'
      fullPath: '/settings/units'
      preLoaderRoute: typeof AppSettingsUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/accounts/': {
      id: '/_app/money/accounts/'
      path: '/money/accounts'
      fullPath: '/money/accounts/'
      preLoaderRoute: typeof AppMoneyAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/accounts/$accountId': {
      id: '/_app/money/accounts/$accountId'
      path: '/money/accounts/$accountId'
      fullPath: '/money/accounts/$accountId'
      preLoaderRoute: typeof AppMoneyAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/tx/$txId': {
      id: '/_app/money/tx/$txId'
      path: '/money/tx/$txId'
      fullPath: '/money/tx/$txId'
      preLoaderRoute: typeof AppMoneyTxTxIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInsightsRoute: typeof AppInsightsRoute
  AppScanRoute: typeof AppScanRoute
  AppThingsRoute: typeof AppThingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMoneyImportRoute: typeof AppMoneyImportRoute
  AppMoneyInboxRoute: typeof AppMoneyInboxRoute
  AppPantryProductIdRoute: typeof AppPantryProductIdRoute
  AppPantryJournalRoute: typeof AppPantryJournalRoute
  AppPantryListRoute: typeof AppPantryListRoute
  AppPlacesPlaceIdRoute: typeof AppPlacesPlaceIdRoute
  AppPlacesLabelsRoute: typeof AppPlacesLabelsRoute
  AppSCodeRoute: typeof AppSCodeRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsCategoriesRoute: typeof AppSettingsCategoriesRoute
  AppSettingsDevicesRoute: typeof AppSettingsDevicesRoute
  AppSettingsDiagnosticsRoute: typeof AppSettingsDiagnosticsRoute
  AppSettingsUnitsRoute: typeof AppSettingsUnitsRoute
  AppMoneyIndexRoute: typeof AppMoneyIndexRoute
  AppPantryIndexRoute: typeof AppPantryIndexRoute
  AppPlacesIndexRoute: typeof AppPlacesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppMoneyAccountsAccountIdRoute: typeof AppMoneyAccountsAccountIdRoute
  AppMoneyTxTxIdRoute: typeof AppMoneyTxTxIdRoute
  AppMoneyAccountsIndexRoute: typeof AppMoneyAccountsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInsightsRoute: AppInsightsRoute,
  AppScanRoute: AppScanRoute,
  AppThingsRoute: AppThingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppMoneyImportRoute: AppMoneyImportRoute,
  AppMoneyInboxRoute: AppMoneyInboxRoute,
  AppPantryProductIdRoute: AppPantryProductIdRoute,
  AppPantryJournalRoute: AppPantryJournalRoute,
  AppPantryListRoute: AppPantryListRoute,
  AppPlacesPlaceIdRoute: AppPlacesPlaceIdRoute,
  AppPlacesLabelsRoute: AppPlacesLabelsRoute,
  AppSCodeRoute: AppSCodeRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsCategoriesRoute: AppSettingsCategoriesRoute,
  AppSettingsDevicesRoute: AppSettingsDevicesRoute,
  AppSettingsDiagnosticsRoute: AppSettingsDiagnosticsRoute,
  AppSettingsUnitsRoute: AppSettingsUnitsRoute,
  AppMoneyIndexRoute: AppMoneyIndexRoute,
  AppPantryIndexRoute: AppPantryIndexRoute,
  AppPlacesIndexRoute: AppPlacesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppMoneyAccountsAccountIdRoute: AppMoneyAccountsAccountIdRoute,
  AppMoneyTxTxIdRoute: AppMoneyTxTxIdRoute,
  AppMoneyAccountsIndexRoute: AppMoneyAccountsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  NotInvitedRoute: NotInvitedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
