"""Writes src/roots.h: the root certificates the scale trusts for HTTPS to Supabase, taken from a local
Mozilla CA bundle (Git for Windows ships one). Supabase's functions and storage are served by Cloudflare
with Google Trust Services certificates today (WE1 -> GTS Root R4; the GlobalSign cross-sign isn't
needed and Mozilla no longer trusts that root);
Cloudflare also uses Let's Encrypt. Pinning these roots (not the server certificate) keeps HTTPS
verified and survives certificate renewals and a switch between these CAs.

    py tools/make-roots.py ["C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt"]
"""
import pathlib
import re
import subprocess
import sys

WANTED = [
    "GTS Root R1",
    "GTS Root R3",
    "GTS Root R4",
    "ISRG Root X1",
    "ISRG Root X2",
]
BUNDLE = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt")
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "roots.h"
OPENSSL = "C:/Program Files/Git/mingw64/bin/openssl.exe"


def info(pem: str) -> tuple[str, str, str]:
    out = subprocess.run(
        [OPENSSL, "x509", "-noout", "-subject", "-enddate", "-fingerprint", "-sha256", "-nameopt", "RFC2253"],
        input=pem, capture_output=True, text=True, check=True,
    ).stdout
    cn = re.search(r"CN=([^,\n]+)", out)
    end = re.search(r"notAfter=(.+)", out)
    fp = re.search(r"Fingerprint=([0-9A-F:]+)", out)
    return (cn.group(1).strip() if cn else "", end.group(1).strip() if end else "", fp.group(1) if fp else "")


def main():
    text = BUNDLE.read_text(encoding="utf-8", errors="replace")
    pems = re.findall(r"-----BEGIN CERTIFICATE-----.+?-----END CERTIFICATE-----", text, re.S)
    found = {}
    for pem in pems:
        cn, end, fp = info(pem + "\n")
        if cn in WANTED and cn not in found:
            found[cn] = (pem, end, fp)
    missing = [w for w in WANTED if w not in found]
    if missing:
        sys.exit(f"not in {BUNDLE}: {missing}")
    lines = [
        "// Generated by tools/make-roots.py from the local Mozilla CA bundle. Do not edit.",
        "// Root certificates trusted for HTTPS to Supabase (functions + storage behind Cloudflare).",
        "#pragma once",
        "",
        "static const char kRootCAs[] =",
    ]
    for cn in WANTED:
        pem, end, fp = found[cn]
        lines.append(f"    // {cn} · valid until {end}")
        lines.append(f"    // SHA-256 {fp}")
        for row in pem.strip().splitlines():
            lines.append(f'    "{row}\\n"')
    lines[-1] = lines[-1] + ";"
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    for cn in WANTED:
        print(f"{cn:20} until {found[cn][1]}")
    print(f"-> {OUT}")


if __name__ == "__main__":
    main()
