"""Packs tools/voice/<ID>.wav (16 kHz 16-bit mono, from make-voice.ps1) into src/voice_data.h as IMA
ADPCM (4 bits per sample, low nibble first), in the order of lib/speech/src/clips.h. Silence at the
start and end of each clip is trimmed so numbers run together naturally ("twenty four grams").

    py tools/wav2adpcm.py
"""
import pathlib
import re
import struct
import sys
import wave

ROOT = pathlib.Path(__file__).resolve().parent.parent
CLIPS = ROOT / "lib" / "speech" / "src" / "clips.h"
VOICE = ROOT / "tools" / "voice"
OUT = ROOT / "src" / "voice_data.h"

INDEX = [-1, -1, -1, -1, 2, 4, 6, 8, -1, -1, -1, -1, 2, 4, 6, 8]
STEPS = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97,
    107, 118, 130, 143, 157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796,
    876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871,
    5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623,
    27086, 29794, 32767,
]


def trim(samples, threshold=350, pad=400):
    loud = [i for i, s in enumerate(samples) if abs(s) > threshold]
    if not loud:
        return samples[:1600]
    return samples[max(0, loud[0] - pad): min(len(samples), loud[-1] + pad)]


def encode(samples):
    pred, index = samples[0] if samples else 0, 0
    start = (pred, index)
    out = bytearray()
    nib = None
    for s in samples:
        step = STEPS[index]
        diff = s - pred
        code = 0
        if diff < 0:
            code = 8
            diff = -diff
        delta = step >> 3
        if diff >= step:
            code |= 4
            diff -= step
            delta += step
        if diff >= step >> 1:
            code |= 2
            diff -= step >> 1
            delta += step >> 1
        if diff >= step >> 2:
            code |= 1
            delta += step >> 2
        pred = pred - delta if code & 8 else pred + delta
        pred = max(-32768, min(32767, pred))
        index = max(0, min(88, index + INDEX[code]))
        if nib is None:
            nib = code
        else:
            out.append(nib | (code << 4))
            nib = None
    if nib is not None:
        out.append(nib)
    return start, bytes(out)


def main():
    ids = re.findall(r'CLIP\((\w+),\s*"[^"]*"\)', CLIPS.read_text(encoding="utf-8"))
    table, data = [], bytearray()
    for cid in ids:
        path = VOICE / f"{cid}.wav"
        if not path.exists():
            sys.exit(f"missing {path} - run tools/make-voice.ps1 first")
        with wave.open(str(path), "rb") as w:
            if w.getframerate() != 16000 or w.getsampwidth() != 2 or w.getnchannels() != 1:
                sys.exit(f"{path}: must be 16 kHz 16-bit mono")
            raw = w.readframes(w.getnframes())
        samples = trim(list(struct.unpack(f"<{len(raw) // 2}h", raw)))
        (pred, index), enc = encode(samples)
        table.append((len(data), len(samples), pred, index, cid))
        data += enc
    lines = [
        "// Generated by tools/wav2adpcm.py from tools/voice/*.wav (make-voice.ps1). Do not edit.",
        "// IMA ADPCM, 16 kHz mono, 4 bits per sample, low nibble first; order = lib/speech/src/clips.h.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "struct VoiceClip {",
        "  uint32_t offset;",
        "  uint32_t samples;",
        "  int16_t pred0;",
        "  uint8_t index0;",
        "};",
        "",
        f"static const VoiceClip kVoiceClips[{len(table)}] = {{",
    ]
    for off, n, pred, index, cid in table:
        lines.append(f"    {{{off}, {n}, {pred}, {index}}},  // {cid}")
    lines.append("};")
    lines.append("")
    lines.append(f"static const uint8_t kVoiceData[{len(data)}] = {{")
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i: i + 24]) + ",")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    secs = sum(n for _, n, *_ in table) / 16000
    print(f"{len(table)} clips, {secs:.1f} s of speech, {len(data) / 1024:.0f} KB -> {OUT}")


if __name__ == "__main__":
    main()
